apiVersion: v1
kind: Service
metadata:
  name: final-assessment-service
spec:
  selector:
    app: final-assessment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
